name:                hschema-aeson
version:             0.0.1.1
category:            Data,Schema,JSON
github:              "alonsodomin/haskell-schema"
license:             LGPL-3
license-file:        LICENSE
author:              "Antonio Alonso Dominguez"
maintainer:          "alonso.domin@gmail.com"
copyright:           "2018 Antonio Alonso Dominguez"

extra-source-files:
- README.md
- ChangeLog.md
- test/*.json

# Metadata used when publishing your package
synopsis:            Describe schemas for your Haskell data types.

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alonsodomin/haskell-schema#readme>

dependencies:
- aeson
- contravariant
- hschema >= 0.0.1.0 && < 0.0.2.0
- hschema-prettyprinter >= 0.0.1.0 && < 0.0.2.0
- hschema-quickcheck >= 0.0.1.0 && < 0.0.2.0
- base >= 4.7 && < 5
- comonad >= 5.0 && < 5.1
- mtl
- natural-transformation
- lens
- free
- QuickCheck
- quickcheck-instances
- prettyprinter
- prettyprinter-ansi-terminal
- scientific
- text
- time
- unordered-containers
- vector

library:
  source-dirs: src

tests:
  hschema-aeson-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - convertible
    - directory
    - hschema
    - hschema-aeson
    - hspec
