name:                hschema
version:             0.0.1.0
category:            Data,Schema
github:              "alonsodomin/haskell-schema"
license:             BSD3
author:              "Antonio Alonso Dominguez"
maintainer:          "alonso.domin@gmail.com"
copyright:           "2018 Antonio Alonso Dominguez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Describing Haskell data types as schemas and obtain free generators, JSON codecs, pretty printers, etc.

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alonsodomin/haskell-schema#readme>

dependencies:
- base >= 4.7 && < 5
- comonad >= 5.0 && < 5.1
- mtl
- natural-transformation
- lens
- free
- text
- vector

library:
  source-dirs: src

