on: [push]

name: build

jobs:
  build:
    name: Build
    strategy:
      matrix:
        ghc: ['8.10']
        stack: ['latest']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ matrix.ghc }}
          # cabal-version: 'latest'. Omitted, but defalts to 'latest'
          enable-stack: true
          stack-version: ${{ matrix.stack }}
          stack-setup-ghc: true
      
      - run: stack build